"""refresh token rotation

Revision ID: 0caba04c2ae1
Revises: 0cf1441527ec
Create Date: 2025-07-31 11:55:19.221826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0caba04c2ae1'
down_revision: Union[str, Sequence[str], None] = '0cf1441527ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_rotated', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('previous_token_id', sa.Integer(), nullable=True))
    op.create_index('idx_refresh_token_previous', 'refresh_tokens', ['previous_token_id'], unique=False)
    op.create_index('idx_refresh_token_rotated', 'refresh_tokens', ['is_rotated'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_previous_token_id'), 'refresh_tokens', ['previous_token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_previous_token_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_rotated', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_previous', table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'previous_token_id')
    op.drop_column('refresh_tokens', 'rotated_at')
    op.drop_column('refresh_tokens', 'is_rotated')
    # ### end Alembic commands ###
