"""make_band_owner_non_nullable

Revision ID: 407106d49b66
Revises: d26c51e9f683
Create Date: 2025-08-08 10:33:34.085079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407106d49b66'
down_revision: Union[str, Sequence[str], None] = 'd26c51e9f683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete existing bands that don't have created_by_user_id
    op.execute("DELETE FROM bands WHERE created_by_user_id IS NULL")
    
    # Make the column non-nullable
    op.alter_column('bands', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bands', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
