"""Add playlist sharing and collaboration fields

Revision ID: 51eb42f5babc
Revises: 95b5ebff5e7a
Create Date: 2025-08-12 03:31:03.437557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eb42f5babc'
down_revision: Union[str, Sequence[str], None] = '95b5ebff5e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.add_column('playlists', sa.Column('allow_collaboration', sa.Boolean(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE playlists SET allow_collaboration = FALSE WHERE allow_collaboration IS NULL")
    
    # Make the column NOT NULL after setting default values
    op.alter_column('playlists', 'allow_collaboration', nullable=False)
    
    op.create_unique_constraint(None, 'playlists', ['share_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='unique')
    op.drop_column('playlists', 'allow_collaboration')
    op.drop_column('playlists', 'share_token')
    # ### end Alembic commands ###
