"""add_is_cleared_to_history

Revision ID: 95b5ebff5e7a
Revises: 407106d49b66
Create Date: 2025-08-11 06:37:39.301845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b5ebff5e7a'
down_revision: Union[str, Sequence[str], None] = '407106d49b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('is_cleared', sa.Boolean(), nullable=False))
    op.create_index('idx_history_cleared', 'histories', ['is_cleared'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_cleared', table_name='histories')
    op.drop_column('histories', 'is_cleared')
    # ### end Alembic commands ###
