"""add_band_owner_field

Revision ID: d26c51e9f683
Revises: 0caba04c2ae1
Create Date: 2025-08-08 10:30:29.755232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26c51e9f683'
down_revision: Union[str, Sequence[str], None] = '0caba04c2ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bands', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bands', type_='foreignkey')
    op.drop_column('bands', 'created_by_user_id')
    # ### end Alembic commands ###
